### PR TITLE
Bidirectional input masking for RelformerLM

### PR DESCRIPTION
**Pull request by syzymon**

### CODE REVIEW

**Comment by PiotrNawrot** [comment]
@googlebot I consent.

**Comment by PiotrNawrot** [comment]
@googlebot I fixed it.

**Comment by syzymon** [comment]
@googlebot I fixed it.

**Comment by PiotrNawrot** [comment]
@googlebot I fixed it.

**Comment by PiotrNawrot** [comment]
@googlebot I consent.

**Review by sawravchy — APPROVED** [review]

**Pull request closed without merging**
