### PR TITLE
Update text_generation.ipynb to support Trax 1.3.3

### PR DESCRIPTION
**Pull request by jalammar**
Update Reformer Text Generation notebook to work on 1.3.3

### CODE REVIEW

**Comment by jalammar** [comment]
This resolves #759.

I updated everything that broke the old notebook. 

A couple of things I'd love feedback on are:

- It's hard pinned to Trax 1.3.3 and no longer hardpinned to the jax and jaxlib versions. Is that okay? Or should we remove all hard pins.
- `gin.parse_config("""LSHCausalAttention.n_hashes = 4""")` was throwing an error so I commented it. We can either remove that cell or change it to the correct config.

**Comment by afrozenator** [comment]
Thanks a lot for the PR @jalammar !! (Big fan of your illustrations!)

Let's get rid of the hard pins! (It's a holdover from the paper submission/rebuttal as a guard against checkpoint incompatibility changes)

`s/LSHCausalAttention/LSHSelfAttention` should do the trick, the gin in a few cells above was updated, we may have missed the last block

Remove model.pkl.gz -- thanks for noting that!

**Comment by jalammar** [comment]
Thank you @afrozenator! (Glad you like the illustrations! I'm working on a few more for Trax!)

Great, I have now removed the hard pins, adjusted the gin config, and renamed the file name. Happy to address anything else if there's any more feedback.

**Comment by afrozenator** [comment]
Re: Trax illustrations - That would be wonderful !! Please let us know if we can help (@lukaszkaiser FYI)

This looks good to me, will merge in shortly.

**Comment by afrozenator** [comment]
Many thanks again!

**Comment by jalammar** [comment]
Fantastic! My pleasure!

The illustrations are happening over at #897. I'll start working on a second draft with some more Trax concepts shortly.

**Pull request merged**
