### PR TITLE
Updates NER/Reformer link in Readme

### PR DESCRIPTION
**Pull request by rastringer**
Updates Readme with new link to the NER/Reformer notebook

### CODE REVIEW

**Comment by rastringer** [comment]
@googlebot I signed it!

**Comment by afrozenator** [comment]
Thanks @rastringer - will merge in shortly!

**Comment by afrozenator** [comment]
Hi @rastringer - Thanks again for the PR, we sequentially merged https://github.com/google/trax/pull/1263 which corrected all these links -- so closing the PR now -- thanks again! And PRs welcome all the time!

**Comment by rastringer** [comment]
Thank you @afrozenator and forgive me, I didn't see the earlier PR. Thanks and enjoy the weekend.

**Comment by afrozenator** [comment]
No need to apologize! You did the right thing by fixing what you saw on master -- many thanks for that! Happy Holidays :-)

**Pull request closed without merging**
