### PR TITLE
Relative-Attention update to Funnel Transformer, Funnel Transformer LM implementation

### PR DESCRIPTION
**Pull request by PiotrNawrot**
Relative-Attention Update to Funnel Transformer from https://arxiv.org/pdf/1901.02860.pdf
Funnel Transformer LM implementation - own research

### CODE REVIEW

**Comment by PiotrNawrot** [comment]
@googlebot I consent.

**Comment by syzymon** [comment]
@googlebot I consent.

**Comment by mvxxx** [comment]
@googlebot I consent.

**Comment by PiotrNawrot** [comment]
@googlebot I consent.

**Comment by shadowatyyy** [comment]
@googlebot I consent.

**Pull request merged**
